# Compile the Inno Setup installer from the prepared package payload on Windows.
[CmdletBinding()]
param(
    [Parameter(Mandatory)] [string] $PackageDirectory,
    [Parameter(Mandatory)] [string] $OutputDirectory,
    [string] $InnoCompiler
)
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

if (-not $InnoCompiler) {
    $Command = Get-Command ISCC.exe -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($Command) { $InnoCompiler = $Command.Source }
    if (-not $InnoCompiler) {
        foreach ($ProgramDirectory in @(${env:ProgramFiles(x86)}, $env:ProgramFiles)) {
            if (-not $ProgramDirectory) { continue }
            $Candidate = Join-Path $ProgramDirectory 'Inno Setup 6/ISCC.exe'
            if ([IO.File]::Exists($Candidate)) { $InnoCompiler = $Candidate; break }
        }
    }
}
if (-not $InnoCompiler -or -not [IO.File]::Exists($InnoCompiler)) {
    throw 'Inno Setup 6 compiler (ISCC.exe) was not found. Install Inno Setup 6, pass -InnoCompiler with its full path, or run package.ps1 -SkipInstaller to build only the ZIP.'
}
$InnoCompiler = (Resolve-Path -LiteralPath $InnoCompiler).ProviderPath
$PackageDirectory = (Resolve-Path -LiteralPath $PackageDirectory).ProviderPath
if (-not [IO.Directory]::Exists($PackageDirectory)) { throw "Package directory does not exist: $PackageDirectory" }
$OutputDirectory = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($OutputDirectory)

# ISCC writes only to fresh local NTFS staging. Copy the finished executable
# with .NET so the output directory can also be an SSHFS checkout.
$Stage = Join-Path "$env:LOCALAPPDATA/WslTools/installers" ([guid]::NewGuid().ToString())
[IO.Directory]::CreateDirectory($Stage) | Out-Null
try {
    $Script = Join-Path $Stage 'installer.iss'
    foreach ($Source in @('installer.iss', 'installer-worker.iss')) {
        [IO.File]::Copy((Join-Path $PSScriptRoot $Source), (Join-Path $Stage $Source), $true)
    }
    $CompilerArguments = @("/DPackageDir=$PackageDirectory", "/O$Stage", $Script)
    & $InnoCompiler @CompilerArguments
    if ($LASTEXITCODE -ne 0) { throw "Inno Setup compilation failed (exit code $LASTEXITCODE)." }
    $InstallerName = 'WslTools-0.1.0-setup-x64.exe'
    $Installer = Join-Path $Stage $InstallerName
    if (-not [IO.File]::Exists($Installer)) { throw "Inno Setup did not produce $InstallerName." }
    [IO.Directory]::CreateDirectory($OutputDirectory) | Out-Null
    $Destination = Join-Path $OutputDirectory $InstallerName
    [IO.File]::Copy($Installer, $Destination, $true)
    Write-Host "Packaged $Destination"
} finally {
    # This directory was freshly generated by this invocation.
    if ([IO.Directory]::Exists($Stage)) { [IO.Directory]::Delete($Stage, $true) }
}
