[CmdletBinding()]
param()
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
$Root = Split-Path $PSScriptRoot -Parent
$Dist = Join-Path $Root 'dist'
foreach ($File in @('WslTools.dll', 'WslTools.pdb', 'wsl-observer')) {
    if (-not (Test-Path "$Dist/$File")) { throw "Missing $File. Run both build scripts first." }
}

# SSHFS can report identical Windows file IDs for distinct files. Stage on
# local NTFS, just like the native build, instead of copying within that mount.
$Package = Join-Path "$env:LOCALAPPDATA/WslTools/packages" ([guid]::NewGuid().ToString())
$TemporaryArchive = "$Package.zip"
[IO.Directory]::CreateDirectory($Package) | Out-Null
function Copy-PackageFile([string] $Source, [string] $Relative) {
    $Destination = Join-Path $Package $Relative
    [IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($Destination)) | Out-Null
    [IO.File]::Copy($Source, $Destination, $true)
}
try {
    foreach ($File in @('WslTools.dll', 'WslTools.pdb', 'wsl-observer')) { Copy-PackageFile "$Dist/$File" $File }
    foreach ($File in @('README.md', 'LICENSE', 'THIRD_PARTY_NOTICES.md')) { Copy-PackageFile "$Root/$File" $File }
    foreach ($File in @('install.ps1', 'uninstall.ps1', 'setup.ps1', 'setup-common.ps1',
                        'setup-files.ps1', 'setup.cmd', 'uninstall.cmd')) {
        Copy-PackageFile "$Root/scripts/$File" $File
    }
    Copy-PackageFile "$Root/vendor/json.LICENSE.MIT" 'licenses/nlohmann-json.LICENSE.MIT'
    Copy-PackageFile "$Root/vendor/json.LICENSE.MIT" 'vendor/json.LICENSE.MIT'
    Copy-PackageFile "$Root/.deps/sdk/LICENSE.txt" 'licenses/SystemInformer.LICENSE.txt'
    foreach ($File in [IO.Directory]::GetFiles("$Root/docs", '*.md')) {
        Copy-PackageFile $File (Join-Path 'docs' ([IO.Path]::GetFileName($File)))
    }
    foreach ($Directory in @('licenses', 'relink')) {
        if (Test-Path "$Dist/$Directory") {
            foreach ($File in [IO.Directory]::GetFiles("$Dist/$Directory")) {
                Copy-PackageFile $File (Join-Path $Directory ([IO.Path]::GetFileName($File)))
            }
        }
    }
    $Hashes = Get-FileHash "$Package/WslTools.dll", "$Package/WslTools.pdb", "$Package/wsl-observer" -Algorithm SHA256
    $Hashes | ForEach-Object { "$($_.Hash.ToLowerInvariant())  $([IO.Path]::GetFileName($_.Path))" } |
        Set-Content "$Package/SHA256SUMS.txt" -Encoding ascii
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    [IO.Compression.ZipFile]::CreateFromDirectory($Package, $TemporaryArchive)
    $Archive = Join-Path $Dist 'WslTools-0.1.0-windows-x64.zip'
    [IO.File]::Copy($TemporaryArchive, $Archive, $true)
    Write-Host "Packaged $Archive"
} finally {
    # Both paths were freshly generated by this invocation, outside the checkout.
    if ([IO.File]::Exists($TemporaryArchive)) { [IO.File]::Delete($TemporaryArchive) }
    if ([IO.Directory]::Exists($Package)) { [IO.Directory]::Delete($Package, $true) }
}
